// Code generated by coz. DO NOT EDIT.
/**
 * Azure storage wrapper
 * @module the-azure-storage
 */
'use strict'

const TheAzureStorage_ = require('./TheAzureStorage')
const create_ = require('./create')
const policies_ = require('./policies')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheAzureStorage = TheAzureStorage_
exports.create = create_
exports.policies = policies_

module.exports = default__
