// Code generated by coz. DO NOT EDIT.
/**
 * Policy builders
 * @module policies
 */
'use strict'

const publicReadPolicy_ = require('./publicReadPolicy')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.publicReadPolicy = publicReadPolicy_

module.exports = {
  publicReadPolicy: publicReadPolicy_,
}
